#!/bin/bash
#
# Backup Script generated by the Interactive Backup Script Generator
#
# This script performs a backup of the specified source paths, archives them,
# and automatically prunes old backups to save space.
#


# 1. ----- Configurations -----
# Source paths to back up. Add or remove paths as needed.
SOURCE_PATHS=(/home/makasim/workspace/bootdotdev/bookbot /home/makasim/workspace/mthree/aws-creds)
DESTINATION_PATH="/home/makasim/workspace/test2"
BCKP_HISTORY_MAX_NUM=3
ARCHIVE_FORMAT="tar"
LOGFILE_PATH="${DESTINATION_PATH}/backup.log"
TIMESTAMP=$(date +%Y-%m-%d_%H-%M-%S)
BACKUP_FILENAME="backup-${TIMESTAMP}.${ARCHIVE_FORMAT}"

# Redirect all output to logfile
exec &>> $LOGFILE_PATH

# Create destination directory if it doesn't exist
mkdir -p "${DESTINATION_PATH}"

# Determine archiving command based on format
# case "$ARCHIVE_FORMAT" in
#   "tar")
#     ARCHIVE_CMD="tar -cf"
#     ;;
#   "tar.gz")
#     ARCHIVE_CMD="tar -czf"
#     ;;
#   "zip")
#     ARCHIVE_CMD="zip -r"
#     ;;
#   *)
#     echo "[\$(date)] Error: Unsupported archive format '\${ARCHIVE_FORMAT}'." >> "\${LOGFILE_PATH}"
#     exit 1
#     ;;
# esac
ARCHIVE_CMD="tar -cf"


# 2. ----- Perform Backup -----
echo "====================================================================================="
echo "[$(date)] Archiving files to ${BACKUP_FILENAME}..." | tee /dev/tty
${ARCHIVE_CMD} "${DESTINATION_PATH}/${BACKUP_FILENAME}" "${SOURCE_PATHS[@]}"
if [ $? -ne 0 ] ; then
    echo "[$(date)] ERROR: Backup failed. See logs at destination path for details"
    exit 1
fi
echo "[$(date)] Backup successful." | tee /dev/tty

# Clen-up old backups, keeping only a certain amount of newest ones
echo "[$(date)] Cleaning old backups (keeping ${BCKP_HISTORY_MAX_NUM} most recent)..."

ls -t ${DESTINATION_PATH}/backup-*.${ARCHIVE_FORMAT} | tail -n +$((BCKP_HISTORY_MAX_NUM + 1)) | xargs rm -f 
if [ $? -eq 0 ]; then
    echo "[$(date)] Cleanup complete."
else
    echo "[$(date)] Cleaning failed."
fi

echo "[$(date)] Backup script finished." | tee /dev/tty

exit 0